object_detection_input:
  lidars:
    status: 'ON'
    topics:
      lidar2: '/sim/lidar2'
      lidar3: '/sim/lidar3'
      lidar7: '/sim/lidar7'
      lidar9: '/sim/lidar9'

  cameras:
    status: 'OFF'
    topics:
      camera1: '/sim/camera1'
