rsu_coordinates:
  lidars:
    lidar2:
      x: 4501.208
      y: 72916.910
      z: 23.76 
      yaw: 244.84  # +0
      pitch: 5.0
      roll: 0.0
    lidar3:
      x: 4499.972
      y: 72926.0
      z: 23.72
      yaw: 333.579  # 
      pitch: 5.0
      roll: 0.0
    lidar7:
      x: 4534.582
      y: 72962.160
      z: 23.75 
      yaw: 152.7 # 
      pitch: 5.0
      roll: 0.0
    lidar9:
      x: 4520.045
      y: 72935.60
      z: 23.85
      yaw: 244.84 # 
      pitch: 5.0
      roll: 0.0

  cameras:
    camera1:
      x: 4501.3804
      y: 72917.1
      z: 5.0
      yaw: 334
      pitch: 5.0
      roll: 0.0
    camera2:
      x: 4499.9434
      y: 72926.1
      z: 5.0
      yaw: 334
      pitch: 5.0
      roll: 0.0